name: Build

on:
  push:
    branches: [master]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
  build_library:
    name: Build Player library
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: ./gradlew --no-daemon --stacktrace build
  build_example:
    name: Build Player example
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Change directory ./example
        run: cd ./example
      - name: Build
        run: ./gradlew --no-daemon --stacktrace assembleRelease
