name: Build

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build Player library
        run: ./gradlew --no-daemon --stacktrace build
